# Generated by Django 4.2.11 on 2025-11-24 17:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['departement', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CreneauTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('heure_pause_debut', models.TimeField(blank=True, null=True)),
                ('heure_pause_fin', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['societe', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_equipement', models.CharField(choices=[('casque', 'Casque'), ('pc', 'PC'), ('laptop', 'Laptop'), ('souris', 'Souris'), ('telephone', 'Téléphone'), ('carte_sim', 'Carte SIM'), ('ecran', 'Écran'), ('clavier', 'Clavier'), ('docking', 'Docking Station'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_disponible', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['type_equipement', 'nom'],
                'unique_together': {('nom', 'type_equipement')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['societe', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='OutilTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('genre', models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin'), ('autre', 'Autre')], max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('mail_professionnel', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_professionnel', models.CharField(blank=True, max_length=20, null=True)),
                ('extension_3cx', models.CharField(blank=True, max_length=10, null=True)),
                ('poste', models.CharField(blank=True, max_length=255, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('conge', 'Congé'), ('arret_maladie', 'Arrêt maladie')], default='actif', max_length=50)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('en_poste', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries', to='api.circuit')),
                ('creneau_travail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries', to='api.creneautravail')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries', to='api.departement')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries', to='api.grade')),
                ('responsable_direct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordonnes', to='api.salarie')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('activite', models.CharField(blank=True, max_length=255, null=True)),
                ('clients', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sociétés',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': "Types d'accès",
            },
        ),
        migrations.CreateModel(
            name='TypeApplicationAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': "Types d'accès application",
            },
        ),
        migrations.CreateModel(
            name='TravauxExceptionnels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_travail', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('nombre_heures', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('description_travail', models.TextField(default='Travaux exceptionnels')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('validée_direct', 'Validée par responsable'), ('validée_service', 'Validée par responsable service'), ('approuvée', 'Approuvée'), ('rejetée', 'Rejetée')], default='brouillon', max_length=50)),
                ('valide_par_direct', models.BooleanField(default=False)),
                ('date_validation_direct', models.DateTimeField(blank=True, null=True)),
                ('valide_par_service', models.BooleanField(default=False)),
                ('date_validation_service', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux_exceptionnels', to='api.salarie')),
            ],
            options={
                'ordering': ['-date_travail'],
            },
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conges_acquis', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('conges_utilises', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('conges_restants', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
                ('salarie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_conge', to='api.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_responsable', to='api.salarie')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.societe')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['societe', 'nom'],
                'unique_together': {('societe', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='salarie',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries', to='api.service'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='api.societe'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_salarie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('admin', 'Administrateur'), ('rh', 'Responsable RH'), ('it', 'Responsable Informatique'), ('daf', 'DAF (Directeur Admin Financier)'), ('comptable', 'Comptable'), ('responsable_service', 'Responsable de Service'), ('salarie', 'Salarié')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_view_salaries', models.BooleanField(default=False)),
                ('can_edit_salaries', models.BooleanField(default=False)),
                ('can_validate_requests', models.BooleanField(default=False)),
                ('can_view_financial', models.BooleanField(default=False)),
                ('can_edit_financial', models.BooleanField(default=False)),
                ('can_manage_it', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateurs', models.ManyToManyField(related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HoraireSalarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('heure_pause_debut', models.TimeField(blank=True, null=True)),
                ('heure_pause_fin', models.TimeField(blank=True, null=True)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires_supplementaires', to='api.salarie')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueSalarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changement', models.DateField(auto_now_add=True)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade_ancien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_ancien', to='api.grade')),
                ('grade_nouveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_nouveau', to='api.grade')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='api.salarie')),
                ('service_ancien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_ancien', to='api.service')),
                ('service_nouveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_nouveau', to='api.service')),
            ],
            options={
                'ordering': ['-date_changement'],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.societe'),
        ),
        migrations.CreateModel(
            name='FichePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(default='Description du poste')),
                ('taches', models.TextField(default='Tâches principales')),
                ('competences_requises', models.TextField(blank=True, null=True)),
                ('moyens_correction', models.TextField(blank=True, null=True)),
                ('problemes', models.TextField(blank=True, null=True)),
                ('propositions', models.TextField(blank=True, null=True)),
                ('defauts', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_revision', 'En révision'), ('archivé', 'Archivé')], default='actif', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grade')),
                ('responsable_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.salarie')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_poste', to='api.service')),
            ],
            options={
                'ordering': ['service', 'titre'],
                'unique_together': {('service', 'titre')},
            },
        ),
        migrations.CreateModel(
            name='FicheParametresUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='light', max_length=50)),
                ('langue', models.CharField(default='fr', max_length=10)),
                ('notifications_actives', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipementInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date_affectation', models.DateField()),
                ('date_retrait', models.DateField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('bon', 'Bon état'), ('usure', 'Usure légère'), ('defaut', 'Défaut'), ('hors_service', 'Hors service')], default='bon', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='api.equipement')),
                ('salarie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='api.salarie')),
            ],
            options={
                'ordering': ['-date_affectation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSalarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('fiche_paie', 'Fiche de paie'), ('contrat', 'Contrat'), ('attestation_salaire', 'Attestation de salaire'), ('attestation_travail', 'Attestation de travail'), ('demande_demission', 'Demande de démission'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('titre', models.CharField(default='Document', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('date_document', models.DateField(blank=True, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('accessible_par_salarie', models.BooleanField(default=True)),
                ('accessible_par_admin', models.BooleanField(default=True)),
                ('accessible_par_rh', models.BooleanField(default=True)),
                ('accessible_par_daf', models.BooleanField(default=True)),
                ('accessible_par_comptable', models.BooleanField(default=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.salarie')),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='api.societe'),
        ),
        migrations.CreateModel(
            name='DemandeSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('motif', models.CharField(default='Sortie exceptionnelle', max_length=255)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('validée_direct', 'Validée par responsable'), ('validée_service', 'Validée par responsable service'), ('approuvée', 'Approuvée'), ('rejetée', 'Rejetée')], default='brouillon', max_length=50)),
                ('valide_par_direct', models.BooleanField(default=False)),
                ('date_validation_direct', models.DateTimeField(blank=True, null=True)),
                ('valide_par_service', models.BooleanField(default=False)),
                ('date_validation_service', models.DateTimeField(blank=True, null=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_sortie', to='api.salarie')),
            ],
            options={
                'ordering': ['-date_sortie'],
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('normal', 'Congé normal'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('sans_solde', 'Congé sans solde'), ('sabbatique', 'Congé sabbatique')], default='normal', max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('validée_direct', 'Validée par responsable direct'), ('validée_service', 'Validée par responsable service'), ('approuvée', 'Approuvée'), ('rejetée', 'Rejetée')], default='brouillon', max_length=50)),
                ('valide_par_direct', models.BooleanField(default=False)),
                ('date_validation_direct', models.DateTimeField(blank=True, null=True)),
                ('commentaire_direct', models.TextField(blank=True, null=True)),
                ('valide_par_service', models.BooleanField(default=False)),
                ('date_validation_service', models.DateTimeField(blank=True, null=True)),
                ('commentaire_service', models.TextField(blank=True, null=True)),
                ('rejete', models.BooleanField(default=False)),
                ('date_rejet', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conge', to='api.salarie')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DemandeAcompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.TextField(default="Demande d'acompte")),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('validée_direct', 'Validée par responsable'), ('validée_service', 'Validée par responsable service'), ('approuvée', 'Approuvée'), ('rejetée', 'Rejetée'), ('payée', 'Payée')], default='brouillon', max_length=50)),
                ('valide_par_direct', models.BooleanField(default=False)),
                ('date_validation_direct', models.DateTimeField(blank=True, null=True)),
                ('valide_par_service', models.BooleanField(default=False)),
                ('date_validation_service', models.DateTimeField(blank=True, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_acompte', to='api.salarie')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.AddField(
            model_name='creneautravail',
            name='societe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_travail', to='api.societe'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to='api.departement'),
        ),
        migrations.CreateModel(
            name='AmeliorationProposee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Amélioration', max_length=255)),
                ('description', models.TextField(default="Description de l'amélioration")),
                ('raison', models.TextField(default='Non spécifiée')),
                ('statut', models.CharField(choices=[('proposal', 'Proposition'), ('examinee', 'Examinée'), ('en_cours', 'En cours'), ('completee', 'Complétée'), ('rejetee', 'Rejetée')], default='proposal', max_length=50)),
                ('date_proposition', models.DateTimeField(auto_now_add=True)),
                ('date_examen', models.DateTimeField(blank=True, null=True)),
                ('priorite', models.IntegerField(default=0)),
                ('responsables', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('examinee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ameliorations_examinees', to=settings.AUTH_USER_MODEL)),
                ('fiche_poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ameliorations', to='api.ficheposte')),
                ('salarie_proposant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.salarie')),
            ],
            options={
                'ordering': ['-date_proposition'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='salarie',
            unique_together={('societe', 'matricule')},
        ),
        migrations.CreateModel(
            name='OutilFichePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatoire', models.BooleanField(default=True)),
                ('fiche_poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outils', to='api.ficheposte')),
                ('outil_travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.outiltravail')),
            ],
            options={
                'unique_together': {('fiche_poste', 'outil_travail')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('societe', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together={('societe', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='creneautravail',
            unique_together={('societe', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='circuit',
            unique_together={('departement', 'nom')},
        ),
        migrations.CreateModel(
            name='AccesSalarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('salarie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acces_locaux', to='api.salarie')),
                ('type_acces', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.typeacces')),
            ],
            options={
                'unique_together': {('salarie', 'type_acces')},
            },
        ),
        migrations.CreateModel(
            name='AccesApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(default='APP', max_length=255)),
                ('identifiant', models.CharField(default='APP_ID', max_length=255)),
                ('mot_de_passe', models.CharField(default='APP_PWD', max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('salarie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acces_applicatif', to='api.salarie')),
                ('type_application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.typeapplicationacces')),
            ],
            options={
                'ordering': ['application'],
                'unique_together': {('salarie', 'application')},
            },
        ),
    ]
