# Generated by Django 4.2.11 on 2025-11-28 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_departement_nombre_circuits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('fichier_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('total_lignes', models.IntegerField(default=0)),
                ('lignes_succes', models.IntegerField(default=0)),
                ('lignes_erreur', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('succes', 'Succès'), ('erreur', 'Erreur'), ('partiel', 'Succès partiel')], default='en_cours', max_length=20)),
                ('details_erreurs', models.JSONField(blank=True, default=dict, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'import",
                'verbose_name_plural': "Logs d'import",
                'ordering': ['-date_creation'],
            },
        ),
    ]
