# Generated by Django 4.2.11 on 2025-12-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_importlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='chef_lieu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
