# Generated by Django 4.2.11 on 2025-12-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_departement_chef_lieu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarie',
            name='departement',
        ),
        migrations.AddField(
            model_name='salarie',
            name='departements',
            field=models.ManyToManyField(blank=True, related_name='salaries', to='api.departement'),
        ),
    ]
