# Generated by Django 4.2.11 on 2025-12-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_salarie_departement_salarie_departements'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='salaries/photos/'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='type_equipement',
            field=models.CharField(choices=[('pc_bureau', 'PC de Bureau'), ('laptop', 'Laptop / Ordinateur Portable'), ('tablette', 'Tablette'), ('all_in_one', 'Ordinateur Tout-en-Un'), ('poste_travail', 'Poste de Travail / Workstation'), ('serveur', 'Serveur'), ('serveur_rack', 'Serveur Rack'), ('nas', 'NAS (Network Attached Storage)'), ('san', 'SAN (Storage Area Network)'), ('mainframe', 'Mainframe'), ('clavier', 'Clavier'), ('souris', 'Souris'), ('souris_trackpad', 'Trackpad / Touchpad'), ('ecran', 'Écran / Moniteur'), ('ecran_tactile', 'Écran Tactile'), ('projecteur', 'Projecteur'), ('data_show', 'Data Show / Videoprojecteur'), ('docking', 'Docking Station'), ('hub_usb', 'Hub USB'), ('adaptateur', 'Adaptateur'), ('chargeur', 'Chargeur / Alimentation'), ('batterie', 'Batterie'), ('casque_audio', 'Casque Audio / Headset'), ('casque_usb', 'Casque USB'), ('microphone', 'Microphone'), ('haut_parleur', 'Haut-Parleur'), ('webcam', 'Webcam / Caméra Web'), ('cable_hdmi', 'Câble HDMI'), ('cable_usb', 'Câble USB'), ('cable_reseau', 'Câble Réseau / RJ45'), ('cable_alimentation', "Câble d'Alimentation"), ('multiprise', 'Multiprise / Rallonge'), ('imprimante_laser', 'Imprimante Laser'), ('imprimante_inkjet', "Imprimante Jet d'Encre"), ('imprimante_3d', 'Imprimante 3D'), ('scanner_document', 'Scanner Document'), ('scanner_code_barre', 'Scanner Code-Barres'), ('scanner_main', 'Scanneur Portable'), ('multifonction', 'Multifonction (Imprim/Scan/Copie/Fax)'), ('photocopieur', 'Photocopieur'), ('fax', 'Fax / Téléfax'), ('routeur', 'Routeur'), ('routeur_wifi', 'Routeur WiFi'), ('switch_reseau', 'Switch Réseau / Commutateur'), ('switch_poe', 'Switch PoE'), ('point_acces_wifi', "Point d'Accès WiFi"), ('point_acces_mesh', "Point d'Accès WiFi Mesh"), ('modem', 'Modem'), ('modem_adsl', 'Modem ADSL'), ('firewall', 'Firewall / Pare-feu'), ('vpn', 'Passerelle VPN'), ('antenne_wifi', 'Antenne WiFi'), ('antenne_5g', 'Antenne 5G'), ('telephone_fixe', 'Téléphone Fixe'), ('telephone_ip', 'Téléphone IP'), ('telephone_mobile', 'Téléphone Mobile / Smartphone'), ('carte_sim', 'Carte SIM'), ('pabx', 'PABX / Autocommutateur'), ('centraliste', 'Poste Centraliste'), ('disque_dur', 'Disque Dur Interne'), ('disque_dur_externe', 'Disque Dur Externe'), ('ssd', 'SSD (Solid State Drive)'), ('ssd_externe', 'SSD Externe'), ('cle_usb', 'Clé USB'), ('cle_usb_securisee', 'Clé USB Sécurisée'), ('lecteur_cd_dvd', 'Lecteur CD/DVD'), ('graveur_dvd', 'Graveur DVD'), ('lecteur_blu_ray', 'Lecteur Blu-Ray'), ('bande_magnetique', 'Bande Magnétique (Sauvegarde)'), ('cartouche_backup', 'Cartouche Backup'), ('ram', 'Mémoire RAM'), ('processeur', 'Processeur / CPU'), ('carte_mere', 'Carte Mère'), ('carte_graphique', 'Carte Graphique / GPU'), ('carte_reseau', 'Carte Réseau'), ('carte_son', 'Carte Son'), ('alimentation_pc', 'Alimentation PC'), ('ventilateur', 'Ventilateur'), ('boitier_pc', 'Boîtier PC'), ('radiateur', 'Radiateur'), ('camera_surveillance', 'Caméra Surveillance / IP Cam'), ('camera_thermique', 'Caméra Thermique'), ('dvr_nvr', 'DVR / NVR (Enregistreur Vidéo)'), ('capteur_mouvement', 'Capteur de Mouvement'), ('lecteur_badge', 'Lecteur de Badge / RFID'), ('biometrie_scanner', 'Scanner Biométrique'), ('badge_securite', 'Badge de Sécurité'), ('onduleur_ups', 'Onduleur / UPS (Alimentation Secours)'), ('stabilisateur_tension', 'Stabilisateur de Tension'), ('generatrice', 'Génératrice'), ('clim_serveur', 'Climatisation Salle Serveur'), ('tableau_interactif', 'Tableau Interactif / Smartboard'), ('ecran_interactif', 'Écran Interactif'), ('camera_conference', 'Caméra de Conférence'), ('microphone_conference', 'Microphone de Conférence'), ('systeme_visio', 'Système de Vidéoconférence'), ('lecteur_code_barre_mobile', 'Lecteur Code-Barres Mobile'), ('terminal_pda', 'Terminal PDA'), ('lecteur_rfid', 'Lecteur RFID'), ('imprimante_etiquettes', "Imprimante d'Étiquettes"), ('balance_connectee', 'Balance Connectée'), ('chrono_badge', 'Système de Pointage / Badge Temps'), ('autre_it', 'Autre Équipement IT')], max_length=50),
        ),
    ]
