# Generated by Django 4.2.11 on 2025-12-22 17:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_salarie_photo_alter_equipement_type_equipement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ameliorationproposee',
            options={'ordering': ['-date_proposition'], 'verbose_name': 'Amélioration Proposée', 'verbose_name_plural': 'Améliorations Proposées'},
        ),
        migrations.RemoveField(
            model_name='ameliorationproposee',
            name='responsables',
        ),
        migrations.AddField(
            model_name='ameliorationproposee',
            name='responsable_user',
            field=models.ForeignKey(blank=True, help_text='Responsable assigné pour traiter la proposition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ameliorations_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarie',
            name='email_societe',
            field=models.EmailField(blank=True, help_text='Email société (jean.dupont@msi.fr) - utilisé pour le login', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='password_changed',
            field=models.BooleanField(default=False, help_text='True si salarié a changé son mot de passe initial'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='premiere_connexion',
            field=models.DateTimeField(blank=True, help_text='Date/heure de la première connexion', null=True),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='date_examen',
            field=models.DateTimeField(blank=True, help_text="Date/heure de l'examen par admin", null=True),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='date_proposition',
            field=models.DateTimeField(auto_now_add=True, help_text='Date/heure de création'),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='deadline',
            field=models.DateField(blank=True, help_text='Deadline pour traiter la proposition', null=True),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='description',
            field=models.TextField(default="Description de l'amélioration", help_text='Détails du problème/besoin identifié'),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='examinee_par',
            field=models.ForeignKey(blank=True, help_text='Admin/RH qui a examiné la proposition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ameliorations_examinees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='priorite',
            field=models.IntegerField(default=0, help_text='Priorité 0-10 (0=normal, 10=urgent)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='raison',
            field=models.TextField(default='Non spécifiée', help_text='Raison du changement et objectif/solution proposée'),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='statut',
            field=models.CharField(choices=[('proposal', 'Proposition'), ('examinee', 'Examinée'), ('en_cours', 'En cours'), ('completee', 'Complétée'), ('rejetee', 'Rejetée')], default='proposal', help_text='Statut actuel de la proposition', max_length=50),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='titre',
            field=models.CharField(default='Amélioration', help_text="Titre de la proposition d'amélioration", max_length=255),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Utilisateur Django associé à ce salarié', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_salarie', to=settings.AUTH_USER_MODEL),
        ),
    ]
