# Generated by Django 4.2.11 on 2025-12-29 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_alter_ameliorationproposee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ameliorationproposee',
            options={'ordering': ['-date_proposition']},
        ),
        migrations.RemoveField(
            model_name='ameliorationproposee',
            name='responsable_user',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='email_societe',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='password_changed',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='premiere_connexion',
        ),
        migrations.AddField(
            model_name='ameliorationproposee',
            name='responsables',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='date_examen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='date_proposition',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='description',
            field=models.TextField(default="Description de l'amélioration"),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='examinee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ameliorations_examinees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='priorite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='raison',
            field=models.TextField(default='Non spécifiée'),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='statut',
            field=models.CharField(choices=[('proposal', 'Proposition'), ('examinee', 'Examinée'), ('en_cours', 'En cours'), ('completee', 'Complétée'), ('rejetee', 'Rejetée')], default='proposal', max_length=50),
        ),
        migrations.AlterField(
            model_name='ameliorationproposee',
            name='titre',
            field=models.CharField(default='Amélioration', max_length=255),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_salarie', to=settings.AUTH_USER_MODEL),
        ),
    ]
