# Generated by Django 4.2.11 on 2026-01-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_service_parent_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='parent_service',
        ),
        migrations.AddField(
            model_name='service',
            name='parentservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sousservices', to='api.service'),
        ),
    ]
