# Generated by Django 4.2.11 on 2026-02-02 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_remove_service_parent_service_service_parentservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheposte',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ficheposte',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
