# Generated by Django 4.2.11 on 2026-02-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ficheposte_created_by_ficheposte_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheposte',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ficheposte',
            name='updated_by',
        ),
    ]
