# Generated by Django 4.2.11 on 2026-04-02 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_ficheposte_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='nombre_chauffeurs',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
